[build.environment]
  NODE_VERSION = "24"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"

[build]
  publish = "docs/docs/.vitepress/dist"
  command = "pnpm run netlify-build"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "text/xml; charset=utf-8"
