name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.repository == 'niansi-z/vitepress-theme-niansi'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create Release for Tag
        id: release_tag
        uses: yyx990803/release-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: |
            Please refer to [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/packages/theme/CHANGELOG.md) for details.
